import Head from "next/head";
import { Inter } from "next/font/google";
import MainHeader from "@/components/main-header/main-header";
import HeroSection from "@/components/hero-section/hero-section";
import CheckAuth from "@/components/check-auth";
import LastestArticles from "@/components/posts/latest-posts";
import FloatingActionButton from "@/components/floating-action-button";
import { ToastContainer } from "react-toastify";
import * as React from "react";
import { fetchLatestPosts } from "@/lib/api/http-post";
import Typography from "@mui/material/Typography";

const inter = Inter({ subsets: ["latin"] });

export default function Home(props) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <HeroSection />
      <LastestArticles />
      <FloatingActionButton />
    </>
  );
}
